eCOSystem/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', include('signin.urls'),name='signin'),
    path('oauth/', include('social_django.urls',namespace='social')),
    path('index/', include('index.urls'), name='index'),
    path('profiles/', include('profiles.urls'),name='profiles'),
    path('my_profile_feed/', include('my_profile_feed.urls'),name='my_profile_feed'),
    path('', include('django.contrib.auth.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path

from . import views

app_name='index'
urlpatterns=[
    path('',views.PostListView,name='index'),
    path('post_comments/',views.PostCommentsView, name='PostCommentsView'),
    path('commented/', views.CommentView, name='CommentView'),
    path('deleteCommentView/', views.deleteCommentView, name="deleteCommentView"),
    path('likeView/', views.likeView, name='likeView'),
    path('dislikeView/', views.dislikeView, name='dislikeView'),
    path('deletePostView/', views.deletePostView, name='deletePostView'),
    path('allnotifications/', views.allnotifications, name='allnotifications'),
    path('deletenotification/', views.deletenotification, name='deletenotification'),
    path('logout',views.signout,name='signout'),
    path('social_logout',views.social_logout,name='social_logout')
]

my_profile_feed/urls.py
from django.urls import path
from . import views



app_name='my_profile_feed'

urlpatterns = [
   path('', views.my_profile_feed, name='my_profile_feed'),
   path('customViewProfile/', views.customViewProfile, name="customViewProfile"),
   path('deleteDetailsView/', views.deleteDetailsView, name="deleteDetailsView"),
   path('chatView/', views.chatView, name="chatView"),
   path('showchats/', views.showchats, name="showchats"),
   path('sendChats/', views.sendChats, name="sendChats"),
]

profiles/urls.py
from django.urls import path

from . import views

app_name='profiles'

urlpatterns = [
    path('',views.profileView, name='profiles'),
    path('followingview/',views.FollowingView, name='FollowingView'),
    path('followersview/', views.FollowersView, name='FollowersView'),
    ]

signin/urls.py
from django.urls import include,path

from django.contrib.auth import views as auth_views
from . import views

app_name='signin'

urlpatterns = [

    path('signup', views.signup, name='signup'),
    # path('oauth', include('social_django.urls',namespace='social')),
    path('',views.signin,name='signin'),

    ]

profiles/models.py
from djongo import models

class Follower(models.Model):
    name = models.CharField(max_length=50, blank=True)
    email = models.EmailField()

class Following(models.Model):
    name = models.CharField(max_length=50, blank=True)
    email = models.EmailField()

class Follow(models.Model):
    user_name = models.EmailField()
    follower = models.ArrayModelField(
        model_container = Follower,
    )
    following = models.ArrayModelField(
        model_container = Following,
    )

    def __str__(self):
        return self.user_name

signin/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from signin.models import signup_model


class MyForm(forms.ModelForm):

    class Meta:
        model = signup_model
        fields = ('full_name','phone','email','password','repeat_password')
        widgets={
       'full_name':forms.TextInput(attrs={'placeholder':'Name'}),
       'phone':forms.TextInput(attrs={'placeholder':'Phone'}),
       'email': forms.TextInput(attrs={'placeholder': 'Email'}),
       'password':forms.PasswordInput(attrs={'placeholder':'Password'}),
       'repeat_password':forms.PasswordInput(attrs={'placeholder':'Repeat Password'}),
                 }

    def __init__(self,*args,**kwargs):
        super(MyForm, self).__init__(*args,**kwargs)
        self.fields['full_name'].label = ''
        self.fields['phone'].label = ''
        self.fields['email'].label = ''
        self.fields['password'].label = ''
        self.fields['repeat_password'].label = ''

my_profile_feed/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from signin.models import signup_model
from .forms import ExperienceForm, AddressForm, SkillForm, InterestForm, Education_detailsForm, CertificationsForm,ProfilepicForm
from .models import Experience, Address, Skill, Interest, Education_details, Certifications, user_profile, FollowNotification, Notification, Chats
from profiles.models import Follow, Following, Follower
from index.models import Posts
from django.utils import timezone
import datetime
import pytz
# Create your views here.

#FORM OBJECTS
experience_form = ExperienceForm()
address_form = AddressForm()
skill_form = SkillForm()
interest_form = InterestForm()
education_details_form = Education_detailsForm()
certifications_form = CertificationsForm()


#REGISTRATION VARIABLE
exp_registered = False
addr_registered = False
skl_registered = False
intrst_registered = False
edu_registered = False
cert_registered = False
over_registered = False

#OVERVIEW FIELDS DATA VARIABLE
data_overview = ""

#EXPERIENCE FIELDS DATA VARIABLES
data_company = ""
data_title = ""
data_location = ""
data_work_field = ""
data_from_date = None
data_to_date = None
data_descriptionExp = ""

#ADDRESS FIELD DATA VARIABLES
data_locality = ""
data_city = ""
data_zip = ""
data_country = ""

#SKILL FIELD DATA VARIABLES
data_skill_name = ""

#INTEREST FIELD DATA VARIABLES
data_interest_name = ""

#EDUCATION DETAILS FIELD DATA VARIABLES
data_school = ""
data_school_from = None
data_school_to = None
data_degree = ""
data_study_field = ""
data_descriptionEdu = ""

#CERTIFICATION DETAILS FIELD DATA VARIABLES
data_certification_name = ""
data_authority = ""
data_cert_from = None
data_cert_to = None
data_cert_pic = None


# TO CHAT WITH SOME ONE YOU HAVE TO FOLLOW HIM and HE HAS TO FOLLOW YOU BACK...??

chats = []
chat_name = ""
chat_email = ""
chat_image = None

def showchats(request):
    if request.session.has_key('username'):
        username = request.session['username']
        # user_details as ud
        ud = user_profile.objects.get(user_email=username)
        user_name = ud.user_name
        # chats = []
        # chat_name = ""
        # chat_email = ""
        if request.method == "POST":
            global chat_name
            global chat_email
            global chat_image
            chat_name = request.POST.get('chat_name')
            chat_email = request.POST.get('chat_email')
            chat_image=user_profile.objects.get(user_email=chat_email).user_image
            chat_details = []
            for c in ud.chats:
                if c.receiver_email == chat_email:
                    chat_details.append(c)
                elif c.sender_email == chat_email:
                    chat_details.append(c)


            # chat_timestap = [c.created_on for c in chat_details]
            # zipped_pairs = zip(chat_timestap, chat_details)
            # z = [x for _, x in sorted(zipped_pairs)]
            # z.reverse()
            # chats = z
            global chats
            chats = chat_details
        return chatView(request, chat_email, chat_name, chats, chat_image)
    else:
        return HttpResponseRedirect(reverse_lazy('signin:signin'))

def sendChats(request):
    if request.session.has_key('username'):
        username = request.session['username']
        # user_details as ud
        ud = user_profile.objects.get(user_email=username)
        user_name = ud.user_name
        # chats = []
        # chat_name = ""
        # chat_email = ""

        if request.method == "POST":
            recipient_name = request.POST.get('chat_name')
            recipient_email = request.POST.get('chat_email')

            global chat_name
            global chat_email
            global chat_image
            chat_name = recipient_name
            chat_email = recipient_email
            chat_image = user_profile.objects.get(user_email=chat_email).user_image
            message = request.POST.get('message')

            dt_utcnow = datetime.datetime.now(tz=pytz.UTC)
            created_on = dt_utcnow.astimezone(pytz.timezone('Asia/Kolkata'))
            print(created_on)
            print()
            print()
            print()

            # current user's chats list as chats_list1
            chats_list1 = ud.chats
            chats_list1.append(Chats(sender_name=user_name, sender_email=username, receiver_name=recipient_name, receiver_email=recipient_email, message=message, created_on=created_on))

            user_profile.objects.update_or_create(user_email=username , defaults={'chats': chats_list1,})

            # recipient_details as rd
            rd = user_profile.objects.get(user_email=recipient_email)

            # current user's frined's chats list as chats_list2
            chats_list2 = rd.chats
            chats_list2.append(Chats(sender_name=user_name, sender_email=username, receiver_name=recipient_name, receiver_email=recipient_email, message=message, created_on=created_on))

            user_profile.objects.update_or_create(user_email=recipient_email, defaults={'chats': chats_list2,})

            chat_details = []
            for c in ud.chats:
                if c.receiver_email == chat_email:
                    chat_details.append(c)
                elif c.sender_email == chat_email:
                    chat_details.append(c)

            # chat_timestap = [c.created_on for c in chat_details]
            # zipped_pairs = zip(chat_timestap, chat_details)
            # z = [x for _, x in sorted(zipped_pairs)]
            # z.reverse()
            # chats = z
            global chats
            chats = chat_details
            request.method = ""
        return chatView(request, chat_email, chat_name, chats,chat_image)
    else:
        return HttpResponseRedirect(reverse_lazy('signin:signin'))
    pass


def chatView(request, chat_email="", chat_name="", chats=[],chat_image=None):
    if request.session.has_key('username'):
        username = request.session['username']
        user_name = user_profile.objects.get(user_email=username).user_name
        user_img = user_profile.objects.get(user_email=username).user_image
        # follow_details as fd
        fd = Follow.objects.get(user_name=username)
        # user_details as ud
        ud = user_profile.objects.all()
        following_list = [f.email for f in fd.following]
        follower_list = [f.email for f in fd.follower]
        chats_list = []
        for f in following_list:
            if f in follower_list:
                chats_list.append(ud.filter(user_email=f)[0])
        return render(request, "chat.html", {'chat_image':chat_image,'user_img':user_img,'username':username, 'user_name':user_name, 'chats_list':chats_list, 'chat_email':chat_email, 'chat_name':chat_name, 'chats':chats})
    else:
        return HttpResponseRedirect(reverse_lazy('signin:signin'))

def my_profile_feed(request):
    if request.session.has_key('username'):
        global over_registered
        global exp_registered
        global addr_registered
        global skl_registered
        global intrst_registered
        global edu_registered
        global cert_registered
        over_registered = False
        exp_registered = False
        addr_registered = False
        skl_registered = False
        intrst_registered = False
        edu_registered = False
        cert_registered = False
        username = request.session['username']
        user_name = user_profile.objects.get(user_email=username).user_name
        profile_details = user_profile.objects.get(user_email = username)
        user_img = user_profile.objects.get(user_email=username).user_image

        overview = profile_details.overview
        experience_list = []
        address = profile_details.address
        skill_list = []
        interest_list = []
        edu_details_list = []
        cert_list = []
        experience_list = profile_details.experience
        experience_list.reverse()
        skill_list = profile_details.skills
        skill_list.reverse()
        interest_list = profile_details.interests
        interest_list.reverse()
        edu_details_list = profile_details.education_details
        edu_details_list.reverse()
        cert_list = profile_details.certifications
        cert_list.reverse()

        experience_form = ExperienceForm()
        address_form = AddressForm()
        skill_form = SkillForm()
        interest_form = InterestForm()
        education_details_form = Education_detailsForm()
        certifications_form = CertificationsForm()
        profilepic= ProfilepicForm()
        if request.method == 'POST':
            file = request.POST.get('image_upload')

            if file == 'image_up':
                profilepic = ProfilepicForm(request.POST, request.FILES)
                if profilepic.is_valid():
                    if 'user_image' in request.FILES:
                        user_image = request.FILES['user_image']

                        user_details = user_profile.objects.get(user_email=username)
                        updated_details = {'user_name': user_details.user_name,
                                           'user_email': user_details.user_email,
                                           'overview': user_details.overview,
                                           'user_image': user_image,
                                           'experience': user_details.experience,
                                           'address': user_details.address,
                                           'education_details': user_details.education_details,
                                           'skills': user_details.skills,
                                           'interests': user_details.interests,
                                           'certifications': user_details.certifications
                                           }

signin/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from my_profile_feed.models import Skill, Interest, user_profile, Experience, Address, Education_details, Certifications
from profiles.models import Follow, Following, Follower
from .models import signup_model
from . import forms,models
from django.contrib.auth.models import User

username='/0'
def signin(request):
    if request.session.has_key('username'):
        return signin_a(request)
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        for record in User.objects.all():
            if record.email.upper()==username.upper() and check_password(password, record.password):
                signup_model.objects.filter(email=username).update(password=record.password)
                request.session['username']=username.lower()
                print(request.session['username'])
            
                return HttpResponseRedirect(reverse('index:index'))

    return signup(request)

def signin_a(request):
    if request.session.has_key('username'):
        return render(request,'signin_a.html')

def signup(request):
    username='/0'
    if request.method=='POST':
        print('HELLO')
        if request.session.has_key('username'):

            username= request.session['username']
            print(username)

        myform=forms.MyForm(data=request.POST)
        if myform.is_valid():
            full_name = myform.cleaned_data['full_name']
            phone = myform.cleaned_data['phone']
            email = myform.cleaned_data['email']
            password = myform.cleaned_data['password']
            repeat_password = myform.cleaned_data['repeat_password']
            if password == repeat_password:
                hashed_password = make_password(password)
                signup_model(full_name=full_name, phone=phone, email=email, password=hashed_password,
                            repeat_password=hashed_password).save()

                User(username=full_name, email=email, password=hashed_password).save()

                usr = user_profile(
                    user_name=myform.cleaned_data['full_name'],
                    user_email=myform.cleaned_data['email'],
                    overview="",
                    experience=[],
                    address=Address(locality="", city="", zip="", country=""),
                    skills=[],
                    interests=[],
                    education_details=[],
                    certifications=[],
                    notification = [],
                    follow_notification = [],
                    chats = [])

                usr.save()
                Follow(user_name = myform.cleaned_data['email'], follower=[], following=[]).save()
               

        return render(request,'signin.html',{'myform': myform,'username':username})

    else:
        myform=forms.MyForm()


    return render(request,'signin.html',{'myform': myform,'username':username})

templates/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title></title>

        <style>
          #show_comments {
            display: none;
          }
         </style>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome-font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">




  </head>
  <body>
    <div class="wrapper">
		<header>
			<div class="container">
				<div class="header-data">

					<div class="search-bar">
						<form>
							<input type="text" name="search" placeholder="Search...">
							<button type="submit"><i class="la la-search"></i></button>
						</form>
					</div><!--search-bar end-->
					<nav>
						<ul>
							<li>
								<a href="{% url 'index:index' %}" title="">
									<span><img src="{% static 'images/icon1.png' %}" alt=""></span>
									Home
								</a>
							</li>

							<li>
								<a href="{% url 'profiles:profiles' %}" title="">
									<span><img src="{% static 'images/icon3.png' %}" alt=""></span>
									My Network
								</a>
                                <ul style="background-color: #01579b">
									<li><a href="{% url 'profiles:FollowersView' %}" title="Followers">Followers</a></li>
									<li><a href="{% url 'profiles:FollowingView' %}" title="Followings">Followings</a></li>
								</ul>
							</li>
                            <li>
								<a href="{% url 'my_profile_feed:my_profile_feed' %}" title="">
									<span><img src="{% static 'images/icon4.png' %}" alt=""></span>
									My Profile
								</a>

							</li>

							<li>
								<a  title="Messgage_Header"  href="#" class="not-box-open">
									<span><img src="{% static 'images/icon6.png' %}" alt="" ></span>
									Messages
								</a>
								<div class="notification-box msg">
									<div class="nt-title">
										<h4>Messages</h4>
									</div>
									<div class="nott-list">
                    {% if chats %}
                    <div class="nott-list" style="overflow:scroll; height: 250px">
                    {% for chat in chats %}
                    <div class="notfication-details">
                          <div class="noty-user-img">
                            <img src="{% static 'images/resources/ny-img1.png' %}" alt="">
                          </div>
                          <div class="notification-info">
                            <h3><a href="http://127.0.0.1:8000/my_profile_feed/customViewProfile/?profile_user_email={{ chat.sender_email }}" title="">{{ chat.sender_name }}</a><br></h3>
                            <p>{{ chat.message }}</p>
                                <br>
                              <p style="color: #d6d4e0;">{{ chat.created_on }}</p>
                          </div><!--notification-info -->
                        </div>
                    <hr>
                    {% endfor %}
                  </div><!--nott-list end-->
                    {% else %}
                    <div class="notfication-details">
                      <h3>No messages for you...</h3>
                    </div>
                    {% endif %}

						  				<div class="view-all-nots">
						  					<a href="http://127.0.0.1:8000/my_profile_feed/chatView/" title="" style="background-color: #01579b">View All Messsages</a>
						  				</div>
									</div><!--nott-list end-->
								</div><!--notification-box end-->
							</li>
							<li>
								<a title="Notification_Header" href="#" class="not-box-open">
									<span><img src="{% static 'images/icon7.png' %}" alt=""></span>
									Notification
								</a>
								<div class="notification-box" id="notifcation-div">
									<div class="nt-title">
										<h4>Notifications</h4>

									</div>

                  {% if notifications %}
									<div class="nott-list" style="overflow:scroll; height: 250px">
                  {% for notification in notifications %}
									<div class="notfication-details">
							  				<div class="noty-user-img">
							  					<img src="{% static 'images/resources/ny-img1.png' %}" alt="">
							  				</div>
							  				<div class="notification-info">
							  					<h3><a href="http://127.0.0.1:8000/my_profile_feed/customViewProfile/?profile_user_email={{ notification.author }}" title="">{{ notification.author }}</a><br></h3>
                          {% if "followed" in notification.text %}
                          <p>{{ notification.text }}</p>
                          {% else %}
                          <a href="http://127.0.0.1:8000/index/post_comments/?title={{ notification.post_title }}&author={{ notification.post_author }}"><p>{{ notification.text }}</p></a>
                          {% endif %}
                          <br>
							  					<span>{{ notification.created_on }}</span>
							  				</div><!--notification-info -->
						  				</div>
                  <hr>
									{% endfor %}
                </div><!--nott-list end-->
                  {% else %}
                  <div class="notfication-details" >
                    <h3>No notifications for you...</h3>
                  </div>
                  {% endif %}

									<div class="view-all-nots">
						  					<a href="{% url 'index:allnotifications' %}" title="" style="background-color: #01579b">View All Notification</a>
						  				</div>
								</div><!--notification-box end-->
							</li>
						</ul>
					</nav><!--nav end-->

                <script>
                    $(".not-box-open").on("click", function(){
             $(this).next(".notification-box").toggleClass("active");})
                </script>
					<div class="menu-btn">
						<a href="#" title=""><i class="fa fa-bars"></i></a>
					</div><!--menu-btn end-->
					<div class="user-account">
						<div class="user-info">
                            <a href="#" title=""><img src="{% static 'images/resources/bg-img4.png' %}" alt=""><span>{{ user_name }}</span></a>

							<i class="la la-sort-down" style="margin: 20px"></i>
						</div>
						<div class="user-account-settingss">
							<h3>Online Status</h3>
							<ul class="on-off-status">
								<li>
									<div class="fgt-sec">
										<input type="radio" name="cc" id="c5" checked>
										<label for="c5">
											<span></span>
										</label>
										<small>Online</small>
									</div>
								</li>
							</ul>
							<h3 class="tc"><a href="{% url 'index:signout' %}" title="">Logout</a></h3>
							<h3 class="tc">{% for assoc in backends.associated %}Logged @: {{ assoc.provider }}</h3>{% endfor %}
{#                           <form id="myform" method="post" action="{% url 'social:disconnect' 'google-oauth2' %}">#}
{#                                 {% csrf_token %}#}
{#                                    <input type="button" name="name" value="value" />#}
{#                               <a onclick="document.getElementById('myform').submit();"><h3>Disconnect</h3></a>#}
{#                            </form>#}
{#                        <form action="{% url 'social:disconnect' %} 'google-oauth2'" method="post">{% csrf_token %}#}
{#                            <h3 class="tc"> <button type="submit" value="Disconnect"></button> </h3>#}
{#    </form>#}
{#                            <h3 class="tc">{{ backends.associated.provider }}</h3>#}
						</div><!--user-account-settingss end-->
					</div>
				</div><!--header-data end-->
			</div>
		</header><!--header end-->

    </div>

        {% block body_block %}
        {% endblock %}


    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.range-min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/slick/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/disabled.js' %}"></script>
{#<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>#}
{#<script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>#}
{#<script type="text/javascript" src="{% static "tiny_mce/tiny_mce_src.js" %}"></script>#}
{#<script type="text/javascript" src="{% static "tiny_mce/tiny_mce_popup.js" %}"></script>#}
{#    <script type="text/javascript">#}
{#    CKEDITOR.replace(id, config);#}
{#</script>#}


{#        <script type="text/javascript" src="{% static 'signin/js/jquery.min.js' %}"></script>#}
{#<script type="text/javascript" src="{% static 'signin/js/popper.js' %}"></script>#}
{#<script type="text/javascript" src="{% static 'signin/js/bootstrap.min.js' %}"></script>#}
{#<script type="text/javascript" src="{% static 'signin/js/jquery.range-min.js' %}"></script>#}
{#<script type="text/javascript" src="{% static 'signin/lib/slick/slick.min.js' %}"></script>#}
{#<script type="text/javascript" src="{% static 'signin/js/script.js' %}"></script>#}
{#<script type="text/javascript" src="{% static 'signin/js/disabled.js' %}"></script>#}

  </body>
</html>

templates/followers.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

		<section class="companies-info">
			<div class="container">
				<div class="company-title">
					<h3>Followers</h3>
				</div><!--company-title end-->
				<div class="companies-list">
					<div class="row">
            {% for profile in profiles %}
            {% if profile.user_email in current_user_followers %}

						<div class="col-lg-3 col-md-4 col-sm-6 col-12">
							<div class="company_profile_info">
								<div class="company-up-info">
									<img src="{% static 'images/resources/pf-icon1.png' %}" alt="">
									<h3>{{ profile.user_name }}</h3>

									<h4>@{{ profile.user_email }}</h4>

									<ul>
										<li>
																						<input type="hidden" id="follow_name" name="follow_name" value="{{ profile.user_name }}">
																				 <input type="hidden" id="follow_email" name="follow_email" value="{{ profile.user_email }}">

																						 </li>
										<li><a href="mailto:{{profile.user_email}}" title="" class="message-us"><i class="fa fa-envelope"></i></a></li>
									</ul>

								</div>
                                <a href="http://127.0.0.1:8000/my_profile_feed/customViewProfile/?profile_user_name={{ profile.user_name }}&profile_user_email={{ profile.user_email }}&View+Profile=View+Profile"" title="" class="view-more-pro">View Profile</a>
                            </div>
                        </div>
                                {% endif %}
                                {% endfor %}
							</div><!--company_profile_info end-->
						</div>


					</div>
				</div><!--companies-list end-->
				<div class="process-comm">
					<div class="spinner">
						<div class="bounce1"></div>
						<div class="bounce2"></div>
						<div class="bounce3"></div>
					</div>
				</div><!--process-comm end-->
			</div>
		</section><!--companies-info end-->


	</div><!--theme-layout end-->
{% endblock %}

templates/following.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

		<section class="companies-info">
			<div class="container">
				<div class="company-title">
					<h3>Following</h3>
				</div><!--company-title end-->
				<div class="companies-list">
					<div class="row">
                        {% for profile in profiles %}
                        {% if profile.user_email in current_user_followings %}

						<div class="col-lg-3 col-md-4 col-sm-6 col-12">
							<div class="company_profile_info">
								<div class="company-up-info">
									<img src="{% static 'images/resources/pf-icon1.png' %}" alt="">
									<h3>{{ profile.user_name }}</h3>

									<h4>@{{ profile.user_email }}</h4>

									<ul>
										<li><form action="{% url 'profiles:FollowingView' %}" method="post">{% csrf_token %}
																						<input type="hidden" id="follow_name" name="follow_name" value="{{ profile.user_name }}">
																				 <input type="hidden" id="follow_email" name="follow_email" value="{{ profile.user_email }}">

																						 <input type="submit" value="Unfollow" name="follow_button" class="btn btn-primary" ></form></li>
										<li><a href="mailto:{{profile.user_email}}" title="" class="message-us"><i class="fa fa-envelope"></i></a></li>
									</ul>

								</div>
                                <a href="http://127.0.0.1:8000/my_profile_feed/customViewProfile/?profile_user_name={{ profile.user_name }}&profile_user_email={{ profile.user_email }}&View+Profile=View+Profile"" title="" class="view-more-pro">View Profile</a>
                            </div>
                        </div>
                                {% endif %}
                                {% endfor %}
							</div><!--company_profile_info end-->
						</div>


					</div>
				</div><!--companies-list end-->
				<div class="process-comm">
					<div class="spinner">
						<div class="bounce1"></div>
						<div class="bounce2"></div>
						<div class="bounce3"></div>
					</div>
				</div><!--process-comm end-->
			</div>
		</section><!--companies-info end-->


	</div><!--theme-layout end-->
{% endblock %}